# Generated by Django 5.0.3 on 2025-05-12 18:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('nombre_heures', models.PositiveIntegerField(blank=True, null=True)),
                ('niveau', models.CharField(blank=True, choices=[('L1', 'Débutant'), ('L2', 'Intermédiaire'), ('L3', 'Avancé')], max_length=50, null=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='cours_illustrations/')),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Professeur.professeurs')),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('python', 'Python'), ('power', 'PowerPoint')], max_length=50)),
                ('fichier', models.FileField(upload_to='ressources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'py', 'pptx'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='ressources_illustrations/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='Cours.cours')),
            ],
        ),
    ]
