# Generated by Django 5.0.3 on 2025-05-14 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0001_initial'),
        ('Etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cours.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiants.etudiants')),
            ],
            options={
                'unique_together': {('etudiant', 'cours')},
            },
        ),
    ]
