# Generated by Django 5.0.3 on 2025-05-12 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('etablissement', models.CharField(blank=True, max_length=150)),
                ('niveau_etude', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2')], default='Licence 1', max_length=20)),
                ('filiere', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('nationalite', models.CharField(choices=[('CI', "Côte d'Ivoire"), ('BF', 'Burkina Faso'), ('TG', 'Togo'), ('BJ', 'Bénin'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('CM', 'Cameroun'), ('HA', 'Haïti')], max_length=2)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
